# Generated by Django 5.2.17 on 2026-09-16 10:53

import chat.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from pathlib import Path
import shutil


def protect_existing_attachments(apps, schema_editor):
    Message = apps.get_model("chat", "Message")
    public_root = Path(settings.MEDIA_ROOT).resolve()
    private_root = Path(settings.PRIVATE_MEDIA_ROOT).resolve()
    for message in Message.objects.exclude(attachment="").exclude(attachment__isnull=True).iterator():
        source = (public_root / message.attachment.name).resolve()
        target = (private_root / message.attachment.name).resolve()
        if source.is_relative_to(public_root) and target.is_relative_to(private_root) and source.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(source), str(target))


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(protect_existing_attachments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=chat.storage.PrivateChatStorage(), upload_to=chat.storage.attachment_path),
        ),
        migrations.CreateModel(
            name='ConversationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='unique_chat_preference')],
            },
        ),
    ]
