# Generated by Django 6.1 on 2026-08-23 22:15

import core.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cover', models.ImageField(blank=True, null=True, upload_to='games/covers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('developer', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('requirements', models.TextField(blank=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='games', to='games.genre')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='game_title_idx'), models.Index(fields=['release_date'], name='game_release_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='game_price_non_negative')],
            },
        ),
    ]
