# Generated by Django 5.2.17 on 2026-08-30 21:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='disk_size_gb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='game',
            name='download_url',
            field=models.URLField(blank=True, help_text='Optional real download target for purchased users.', max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Optional wide artwork used by the owned-game library page.', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('disk_size_gb__isnull', True), ('disk_size_gb__gte', 0), _connector='OR'), name='game_disk_size_non_negative'),
        ),
    ]
