# Generated by Django 6.1 on 2026-09-05 14:51

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_disk_size_gb_game_download_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games/screenshots/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.game')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
    ]
