# Generated by Django 5.2.17 on 2026-09-15 11:22

import core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cover', models.ImageField(blank=True, null=True, upload_to='games/dlc/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('hero_image_url', models.URLField(blank=True, max_length=500)),
                ('release_date', models.DateField()),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('disk_size_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlc', to='games.game')),
            ],
            options={
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GameBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cover', models.ImageField(blank=True, null=True, upload_to='games/bundles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('dlc', models.ManyToManyField(blank=True, related_name='bundles', to='games.dlc')),
                ('games', models.ManyToManyField(blank=True, related_name='bundles', to='games.game')),
            ],
            options={
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='dlc',
            constraint=models.UniqueConstraint(fields=('game', 'title'), name='unique_dlc_title_per_game'),
        ),
        migrations.AddConstraint(
            model_name='dlc',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='dlc_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='gamebundle',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='bundle_price_non_negative'),
        ),
    ]
