# Generated by Django 5.2.17 on 2026-08-30 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_disk_size_gb_game_download_url_and_more'),
        ('store', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LibraryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('games', models.ManyToManyField(blank=True, related_name='library_collections', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_library_collection_name_per_user')],
            },
        ),
    ]
