# Generated by Django 5.2.17 on 2026-09-15 11:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_dlc_gamebundle_dlc_unique_dlc_title_per_game_and_more'),
        ('store', '0004_order_totals_and_library_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='games.gamebundle')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='store.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'bundle'), name='unique_order_bundle')],
            },
        ),
        migrations.CreateModel(
            name='CartDLCItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlc_items', to='store.cart')),
                ('dlc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='games.dlc')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('cart', 'dlc'), name='unique_cart_dlc')],
            },
        ),
        migrations.CreateModel(
            name='LibraryDLCItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dlc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_items', to='games.dlc')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_dlc_items', to='store.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_dlc_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('user', 'dlc'), name='unique_library_user_dlc'), models.CheckConstraint(condition=models.Q(('price_at_purchase__gte', 0)), name='library_dlc_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='OrderDLCItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dlc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='games.dlc')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlc_items', to='store.order')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('order', 'dlc'), name='unique_order_dlc'), models.CheckConstraint(condition=models.Q(('price_at_purchase__gte', 0)), name='order_dlc_price_non_negative')],
            },
        ),
    ]
