# Generated by Django 5.2.17 on 2026-09-04

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("community", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="GameReviewImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="reviews/%Y/%m/", validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("jpg", "jpeg", "png", "webp")), core.validators.validate_image_size])),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("review", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="community.gamereview")),
            ],
            options={
                "ordering": ("position", "created_at", "pk"),
                "indexes": [models.Index(fields=["review", "position"], name="review_image_position_idx")],
            },
        ),
    ]
