# Generated by Django 5.2.17 on 2026-09-07 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_review_rating_constraint_and_index'),
        ('games', '0003_gamescreenshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamereview',
            index=models.Index(fields=['user', '-updated_at', '-id'], name='review_user_updated_idx'),
        ),
    ]
