# Generated by Django 5.2.17 on 2026-09-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_enforce_wishlist_ownership_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='community/%Y/%m/'),
        ),
    ]
