export const legal = `
Steamn’t is an educational game storefront and community project. Accounts, purchases, wallet funds, and downloads shown here are for demonstration purposes.|Steamn’t — учебный проект магазина игр и сообщества. Аккаунты, покупки, средства кошелька и загрузки представлены для демонстрации.|Steamn’t — навчальний проєкт магазину ігор і спільноти. Облікові записи, покупки, кошти гаманця та завантаження представлено для демонстрації.
Provide accurate registration details, protect your password, and use the service respectfully. You are responsible for activity under your account.|Указывайте достоверные данные, защищайте пароль и уважайте других пользователей. Вы отвечаете за действия своего аккаунта.|Указуйте достовірні дані, захищайте пароль і поважайте інших користувачів. Ви відповідаєте за дії свого облікового запису.
Checkout records a demo purchase and adds the game to your library. No real money is charged and no commercial license is granted.|Оформление сохраняет демо-покупку и добавляет игру в библиотеку. Реальные деньги не списываются, коммерческая лицензия не предоставляется.|Оформлення зберігає демо-покупку та додає гру до бібліотеки. Реальні кошти не списуються, комерційна ліцензія не надається.
Do not post unlawful, abusive, misleading, or unauthorized content. You may edit or remove content you created. Moderation may hide content that violates these rules.|Не публикуйте незаконные, оскорбительные, вводящие в заблуждение материалы или материалы без разрешения. Вы можете изменять и удалять свои публикации. Модерация может скрыть нарушения.|Не публікуйте незаконні, образливі матеріали, матеріали без дозволу або ті, що вводять в оману. Ви можете змінювати й видаляти свої дописи. Модерація може приховати порушення.
This course project may change or be unavailable during development. Your locally stored data depends on the database used by the operator.|Учебный проект может меняться и быть недоступным при разработке. Сохранность локальных данных зависит от базы данных оператора.|Навчальний проєкт може змінюватися й бути недоступним під час розробки. Збереження локальних даних залежить від бази даних оператора.
Your account stores a username, email, hashed password, profile information, game library, wishlist, orders, and community activity.|В аккаунте хранятся имя, почта, хеш пароля, профиль, библиотека, желаемое, заказы и активность сообщества.|В обліковому записі зберігаються ім’я, пошта, хеш пароля, профіль, бібліотека, бажане, замовлення й активність спільноти.
Your username and content you publish may be visible to others. Privacy settings control visibility of games, wishlist, friends, activity, and online status.|Имя и публикации могут быть видны другим. Настройки приватности управляют видимостью игр, желаемого, друзей, активности и статуса в сети.|Ім’я та дописи можуть бути видимі іншим. Налаштування приватності керують видимістю ігор, бажаного, друзів, активності та статусу в мережі.
Passwords are hashed. Sign-in uses short-lived access tokens and refresh tokens. Do not share your tokens or password.|Пароли хранятся в виде хешей. Вход использует краткосрочные токены доступа и токены обновления. Не передавайте токены и пароль.|Паролі зберігаються у вигляді хешів. Вхід використовує короткострокові токени доступу й токени оновлення. Не передавайте токени й пароль.
Conversation data and attachments are stored for participants. Access to attachments requires an authenticated participant.|История чата и вложения хранятся для участников. Доступ к вложениям требует входа участника чата.|Історія чату й вкладення зберігаються для учасників. Доступ до вкладень потребує входу учасника чату.
You can edit profile information and permanently delete your account in Settings. Deletion removes the account, its demo orders, wallet, library, published content, social connections, profile media, and conversations with their attachments. Other participants lose those conversations too. Contact the operator for a data export before deleting the account.|В настройках можно изменить профиль или навсегда удалить аккаунт. Удалятся демо-заказы, кошелёк, библиотека, публикации, социальные связи, медиа профиля и чаты с вложениями. У других участников эти чаты тоже исчезнут. До удаления запросите экспорт данных у оператора.|У налаштуваннях можна змінити профіль або назавжди видалити обліковий запис. Видаляться демо-замовлення, гаманець, бібліотека, дописи, соціальні зв’язки, медіа профілю й чати з вкладеннями. В інших учасників ці чати також зникнуть. До видалення запросіть експорт даних в оператора.
Steamn’t does not process real payments. Checkout and wallet transactions are demonstrations and do not represent commercial charges.|Steamn’t не обрабатывает реальные платежи. Покупки и операции кошелька демонстрационные и не являются коммерческими списаниями.|Steamn’t не обробляє реальні платежі. Покупки й операції гаманця демонстраційні та не є комерційними списаннями.
An order receipt shows the price recorded at purchase time. It remains in your order history for coursework demonstration.|Чек показывает цену на момент покупки и сохраняется в истории заказов для демонстрации учебного проекта.|Чек показує ціну на момент купівлі та зберігається в історії замовлень для демонстрації навчального проєкту.
Open Order history, choose an order, and select Refund order. Completed orders can be refunded within 14 days. The entire order is refunded to your demo wallet and its games and DLC leave your library. Refund separately purchased DLC before its base game. Repeating the request never adds funds twice. Demo funds have no monetary value.|Откройте историю заказов, выберите заказ и нажмите «Вернуть заказ». Завершённый заказ можно вернуть в течение 14 дней. Вся сумма возвращается в демо-кошелёк, игры и DLC удаляются из библиотеки. Отдельно купленные DLC возвращайте до основной игры. Повторный запрос не удваивает возврат. Демо-средства не имеют денежной ценности.|Відкрийте історію замовлень, оберіть замовлення й натисніть «Повернути замовлення». Завершене замовлення можна повернути протягом 14 днів. Уся сума повертається до демо-гаманця, ігри та DLC вилучаються з бібліотеки. Окремо придбані DLC повертайте до основної гри. Повторний запит не подвоює повернення. Демо-кошти не мають грошової цінності.
For questions about a local deployment, contact the person or team operating that instance.|По вопросам локальной установки обратитесь к её оператору.|Із запитаннями щодо локальної установки зверніться до її оператора.
These terms describe the educational demo service and its local data.|Эти правила описывают учебный демо-сервис и его локальные данные.|Ці правила описують навчальний демо-сервіс і його локальні дані.
`.trim().split('\n').map(line => line.split('|'));
